/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package acp.lab.project1.pages;

import acp.lab.project1.utils.ConnectionManager;
import java.sql.*;
import java.util.LinkedList;
import java.math.BigDecimal;
import acp.lab.project1.utils.DefinedColors;

/**
 *
 * @author addan
 */
public class AdminManagementPage extends javax.swing.JFrame {

    /**
     * Creates new form UserManagementPage
     */
    public AdminManagementPage() {
        initComponents();
        postInit();
    }
    
    private void postInit() {
        Connection con = null;
        try {
            con = ConnectionManager.getConnection();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        if (con == null) return;

        LinkedList<String> ids = new LinkedList<>();
        LinkedList<String> nms = new LinkedList<>();
        try {
            ResultSet rs = con.createStatement().executeQuery("select top 15 UserId, Username from UserDetails where UserId <> " + acp.lab.project1.LoggedInUser.userID);
            while (rs.next()) {
                ids.add(Integer.valueOf(rs.getInt("UserId")).toString());
                nms.add(rs.getString("Username"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        java.awt.GridBagConstraints gridBagConstraints;
        for (int i = 0; i < ids.size(); i++) {
            try {
                ResultSet rs = con.createStatement().executeQuery("select sum(Fine) as fine from Record where UserId = " + ids.get(i));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = i;
                while (rs.next()) {
                    BigDecimal bd = rs.getBigDecimal("fine");
                    if (bd != null)
                        jPanel5.add(new acp.lab.project1.utils.UserRow(ids.get(i), nms.get(i), bd.setScale(2, java.math.RoundingMode.CEILING).toString()), gridBagConstraints);
                    else
                        jPanel5.add(new acp.lab.project1.utils.UserRow(ids.get(i), nms.get(i), "0.00"), gridBagConstraints);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        addBookLabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        addBookLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        removeBookLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        addUserLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        reviewRequestLabel = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        reviewRequestLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(33, 37, 41));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(DefinedColors.backgroundSecondaryColor);
        jPanel2.setMaximumSize(new java.awt.Dimension(256, 720));
        jPanel2.setMinimumSize(new java.awt.Dimension(256, 720));
        jPanel2.setPreferredSize(new java.awt.Dimension(256, 720));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setBackground(DefinedColors.backgroundSecondaryColor);
        jPanel6.setMaximumSize(new java.awt.Dimension(256, 60));
        jPanel6.setMinimumSize(new java.awt.Dimension(256, 60));
        jPanel6.setPreferredSize(new java.awt.Dimension(256, 60));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        jPanel8.setBackground(DefinedColors.backgroundSecondaryColor);
        jPanel8.setMaximumSize(new java.awt.Dimension(256, 60));
        jPanel8.setMinimumSize(new java.awt.Dimension(256, 60));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new java.awt.GridBagLayout());

        addBookLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        addBookLabel.setForeground(new java.awt.Color(255, 255, 255));
        addBookLabel.setText("Add Book");
        addBookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBookLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel8.add(addBookLabel, gridBagConstraints);

        jPanel2.add(jPanel8);

        jPanel11.setBackground(DefinedColors.backgroundSecondaryColor);
        jPanel11.setMaximumSize(new java.awt.Dimension(256, 60));
        jPanel11.setMinimumSize(new java.awt.Dimension(256, 60));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });
        jPanel11.setLayout(new java.awt.GridBagLayout());

        addBookLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        addBookLabel1.setForeground(new java.awt.Color(255, 255, 255));
        addBookLabel1.setText("Update Book");
        addBookLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBookLabel1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel11.add(addBookLabel1, gridBagConstraints);

        jPanel2.add(jPanel11);

        jPanel10.setBackground(DefinedColors.backgroundSecondaryColor);
        jPanel10.setMaximumSize(new java.awt.Dimension(256, 60));
        jPanel10.setMinimumSize(new java.awt.Dimension(256, 60));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new java.awt.GridBagLayout());

        removeBookLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        removeBookLabel.setForeground(new java.awt.Color(255, 255, 255));
        removeBookLabel.setText("Remove Book");
        removeBookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBookLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel10.add(removeBookLabel, gridBagConstraints);

        jPanel2.add(jPanel10);

        jPanel9.setBackground(DefinedColors.backgroundSecondaryColor);
        jPanel9.setMaximumSize(new java.awt.Dimension(256, 60));
        jPanel9.setMinimumSize(new java.awt.Dimension(256, 60));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.setLayout(new java.awt.GridBagLayout());

        addUserLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        addUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        addUserLabel.setText("Add User");
        addUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel9.add(addUserLabel, gridBagConstraints);

        jPanel2.add(jPanel9);

        jPanel12.setBackground(DefinedColors.backgroundSecondaryColor);
        jPanel12.setMaximumSize(new java.awt.Dimension(256, 60));
        jPanel12.setMinimumSize(new java.awt.Dimension(256, 60));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });
        jPanel12.setLayout(new java.awt.GridBagLayout());

        reviewRequestLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        reviewRequestLabel.setForeground(new java.awt.Color(255, 255, 255));
        reviewRequestLabel.setText("Review Requests");
        reviewRequestLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reviewRequestLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel12.add(reviewRequestLabel, gridBagConstraints);

        jPanel2.add(jPanel12);

        logoutPanel.setBackground(DefinedColors.backgroundSecondaryColor);
        logoutPanel.setMaximumSize(new java.awt.Dimension(256, 60));
        logoutPanel.setMinimumSize(new java.awt.Dimension(256, 60));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
        });
        logoutPanel.setLayout(new java.awt.GridBagLayout());

        reviewRequestLabel2.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        reviewRequestLabel2.setForeground(new java.awt.Color(255, 255, 255));
        reviewRequestLabel2.setText("Logout");
        reviewRequestLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reviewRequestLabel2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        logoutPanel.add(reviewRequestLabel2, gridBagConstraints);

        jPanel2.add(logoutPanel);

        jPanel1.add(jPanel2, new java.awt.GridBagConstraints());

        jPanel3.setBackground(new java.awt.Color(33, 37, 41));
        jPanel3.setPreferredSize(new java.awt.Dimension(1024, 720));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(DefinedColors.backgroundPrimaryColor);
        jPanel4.setMaximumSize(new java.awt.Dimension(1280, 120));
        jPanel4.setMinimumSize(new java.awt.Dimension(1280, 120));
        jPanel4.setPreferredSize(new java.awt.Dimension(1024, 120));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jTextField3.setFont(new java.awt.Font("Roboto Condensed", 0, 24)); // NOI18N
        jTextField3.setText("Search for user");
        jTextField3.setPreferredSize(new java.awt.Dimension(820, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(jTextField3, gridBagConstraints);

        jButton1.setBackground(DefinedColors.backgroundSecondaryColor);
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GO");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel4, new java.awt.GridBagConstraints());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(1024, 600));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1024, 600));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1024, 600));

        jPanel5.setBackground(DefinedColors.backgroundPrimaryColor);
        jPanel5.setMaximumSize(new java.awt.Dimension(1022, 598));
        jPanel5.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(jPanel5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel3.add(jScrollPane1, gridBagConstraints);

        jPanel1.add(jPanel3, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBookLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addBookLabelMouseClicked

    private void addUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserLabelMouseClicked

    private void removeBookLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBookLabelMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_removeBookLabelMouseClicked

    private void reviewRequestLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewRequestLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reviewRequestLabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        
        Connection con = null;
        try {
            con = ConnectionManager.getConnection();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        if (con == null) return;

        LinkedList<String> ids = new LinkedList<>();
        LinkedList<String> nms = new LinkedList<>();
        try {
            ResultSet rs = con.createStatement().executeQuery("select top 15 UserId, Username from UserDetails where UserId <> " + acp.lab.project1.LoggedInUser.userID + " and Username like \'%" + jTextField3.getText() + "%\'");
            while (rs.next()) {
                ids.add(Integer.valueOf(rs.getInt("UserId")).toString());
                nms.add(rs.getString("Username"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        java.awt.GridBagConstraints gridBagConstraints;
        for (int i = 0; i < ids.size(); i++) {
            try {
                ResultSet rs = con.createStatement().executeQuery("select sum(Fine) as fine from Record where UserId = " + ids.get(i));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = i;
                while (rs.next()) {
                    BigDecimal bd = rs.getBigDecimal("fine");
                    if (bd != null)
                        jPanel5.add(new acp.lab.project1.utils.UserRow(ids.get(i), nms.get(i), bd.toString()), gridBagConstraints);
                    else
                        jPanel5.add(new acp.lab.project1.utils.UserRow(ids.get(i), nms.get(i), "0.00"), gridBagConstraints);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        
        javax.swing.SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        // TODO add your handling code here:
        acp.lab.project1.pages.ReviewRequestsPage.main(new String[]{});
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
        acp.lab.project1.pages.SignupPage.main(new String[]{});
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jPanel9MouseClicked

    private void addBookLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addBookLabel1MouseClicked

    private void reviewRequestLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewRequestLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reviewRequestLabel2MouseClicked

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        // TODO add your handling code here:
        acp.lab.project1.pages.LoginPage.main(new String[]{});
        setVisible(false);
        dispose();
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        acp.lab.project1.pages.AddBookPage.main(new String[]{});
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
        acp.lab.project1.pages.UpdateBookPage.main(new String[]{});
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
        acp.lab.project1.pages.UpdateBookPage.main(new String[]{});
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jPanel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminManagementPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBookLabel;
    private javax.swing.JLabel addBookLabel1;
    private javax.swing.JLabel addUserLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JLabel removeBookLabel;
    private javax.swing.JLabel reviewRequestLabel;
    private javax.swing.JLabel reviewRequestLabel2;
    // End of variables declaration//GEN-END:variables
}
