/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package acp.lab.project1.pages;
import acp.lab.project1.utils.ConnectionManager;
import acp.lab.project1.utils.ThumbnailManager;
import acp.lab.project1.utils.DefinedColors;
import acp.lab.project1.LoggedInUser;
import java.sql.*;
/**
 *
 * @author addan
 */
public class BookPage extends javax.swing.JFrame {
    private int bookID;
    private String URL;
    private String ISBN;
    private String title;
    private String description;
    private int yearPublished;
    private float rating;
    private int pages;
    private String authors;
    private String categories;
    /**
     * Creates new form AccountPage
     */
    public BookPage(String BID) {
        bookID = Integer.valueOf(BID);
        preInit(BID);
        initComponents();
    }
    
    private void preInit(String BID) {
        authors = "<html><p style='textAlign:center'>";
        categories = "";
        Connection con = null;
        try {
            con = ConnectionManager.getConnection();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        if (con == null) return;
        
        try {
            ResultSet rs = con.createStatement().executeQuery("select * from Book where BookId = " + BID);
            while (rs.next()) {
                URL = rs.getString("ThumbnailURL");
                ISBN = rs.getString("ISBN");
                title = rs.getString("Title");
                description = rs.getString("Description");
                yearPublished = rs.getInt("YearPublished");
                rating = rs.getFloat("Rating");
                pages = rs.getInt("Pages");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        try {
            ResultSet rs = con.createStatement().executeQuery("select FullName from Author where BookId = " + BID);
            while (rs.next()) {
                authors += rs.getString("FullName") + "<br>";
            }
            authors = authors.substring(0, authors.length() - 4) + "</p></html>";
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        try {
            ResultSet rs = con.createStatement().executeQuery("select FullName from Category where BookId = " + BID);
            while (rs.next()) {
                categories += rs.getString("FullName") + ", ";
            }
            categories = categories.substring(0, categories.length() - 2);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        if (rating > 0) return;
        try {
            ResultSet rs = con.createStatement().executeQuery("select avg(Rating) as r from Rating where BookId = " + BID);
            while (rs.next()) {
                rating = rs.getFloat("FullName");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(DefinedColors.backgroundPrimaryColor);
        jPanel2.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel2.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(DefinedColors.backgroundLightColor);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(DefinedColors.whiteColor));
        jPanel1.setMaximumSize(new java.awt.Dimension(640, 640));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 640));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(DefinedColors.backgroundLightColor);
        jPanel4.setMaximumSize(new java.awt.Dimension(250, 325));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBackground(DefinedColors.backgroundLightColor);
        jPanel5.setMaximumSize(new java.awt.Dimension(250, 500));
        jPanel5.setMinimumSize(new java.awt.Dimension(250, 500));
        jPanel5.setPreferredSize(new java.awt.Dimension(250, 500));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 3)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("\\acp\\lab\\project1\\resources\\imgNotFound.jpg"));
        ThumbnailManager.main(new String[]{URL, ISBN});
        String pathToBe = "\\acp\\lab\\project1\\resources\\temp\\" + ISBN + ".png";
        System.out.println(URL);
        try {
            jLabel1.setIcon(new javax.swing.ImageIcon(pathToBe));
        } catch (Exception e) {
            jLabel1.setIcon(new javax.swing.ImageIcon("\\acp\\lab\\project1\\resources\\imgNotFound.jpg"));
        }
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel5.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel2.setForeground(DefinedColors.whiteColor);
        jLabel2.setText(title);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        jPanel5.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel3.setForeground(DefinedColors.whiteColor);
        jLabel3.setText(authors);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel5.add(jLabel3, gridBagConstraints);

        jPanel4.add(jPanel5, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel4, new java.awt.GridBagConstraints());

        jPanel3.setBackground(DefinedColors.backgroundLightColor);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton4.setBackground(DefinedColors.backgroundSecondaryColor);
        jButton4.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jButton4.setForeground(DefinedColors.whiteColor);
        jButton4.setText("Checkout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        jPanel3.add(jButton4, gridBagConstraints);

        jButton5.setBackground(DefinedColors.backgroundSecondaryColor);
        jButton5.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jButton5.setForeground(DefinedColors.whiteColor);
        jButton5.setText("Add/Remove To Cart");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        jPanel3.add(jButton5, gridBagConstraints);

        returnButton.setBackground(DefinedColors.backgroundSecondaryColor);
        returnButton.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        returnButton.setForeground(DefinedColors.whiteColor);
        returnButton.setText("Back");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel3.add(returnButton, gridBagConstraints);

        jButton1.setBackground(DefinedColors.backgroundSecondaryColor);
        jButton1.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jButton1.setForeground(DefinedColors.whiteColor);
        jButton1.setText("Rate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        jPanel3.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel6.setBackground(DefinedColors.backgroundLightColor);
        jPanel6.setMaximumSize(new java.awt.Dimension(375, 500));
        jPanel6.setMinimumSize(new java.awt.Dimension(375, 500));
        jPanel6.setPreferredSize(new java.awt.Dimension(375, 500));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel4.setForeground(DefinedColors.whiteColor);
        jLabel4.setText("Categories: " + categories);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel6.add(jLabel4, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel6.setForeground(DefinedColors.whiteColor);
        jLabel6.setText("<html><div style='width: 350px; height: 275px;'><p>" + acp.lab.project1.utils.StringSplit.breakText(description, 60) + "</p></div></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel6.add(jLabel6, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel5.setForeground(DefinedColors.whiteColor);
        jLabel5.setText(Integer.valueOf(pages).toString() + " pages - " + rating + " out 5 stars");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel6.add(jLabel5, gridBagConstraints);
        javax.swing.SwingUtilities.updateComponentTreeUI(this);

        jPanel1.add(jPanel6, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(246, 544, 247, 545);
        jPanel2.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CheckoutPage.main(new String[]{});
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < LoggedInUser.cart.size(); i++) {
            if (LoggedInUser.cart.get(i) == bookID) {
                LoggedInUser.cart.remove(i);
                javax.swing.JOptionPane.showMessageDialog(this, "Item removed from cart!", 
                                   "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        
        java.text.SimpleDateFormat formatter = new java.text.SimpleDateFormat("yyyy-MM-dd");
        java.util.Date refDate = null;
        try {
            refDate = formatter.parse("1999-12-31");
        } catch (java.text.ParseException e) {
            e.printStackTrace();
        }
        
        for (int i = 0; i < LoggedInUser.booksBorrowed.size(); i++) {
            if (LoggedInUser.booksBorrowed.get(i).ID == bookID && LoggedInUser.booksBorrowed.get(i).returnDate.compareTo(refDate) == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "You already have this book borrowed!", 
                                   "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if (LoggedInUser.cart.size() + LoggedInUser.borrowedBookCount == (LoggedInUser.userType == 1 ? 3 : 5)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Number of items in cart and already borrowed exceeds your limit!", 
                                   "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        LoggedInUser.cart.add(bookID);
        javax.swing.JOptionPane.showMessageDialog(this, "Item added to cart!", 
                                   "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        SearchPage.main(new String[]{});
        setVisible(false);
        dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RatePage.main(new String[]{Integer.valueOf(bookID).toString()});
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookPage(args[0]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
