/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package acp.lab.project1.pages;
import acp.lab.project1.utils.ConnectionManager;
import acp.lab.project1.utils.DefinedColors;
import acp.lab.project1.LoggedInUser;
import acp.lab.project1.Book;
import java.sql.*;
import java.util.LinkedList;
/**
 *
 * @author addan
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginPage() {
        LoggedInUser.reset();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        forgetPasswordLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        // jPanel1.setBackground(new java.awt.Color(89, 13, 34));
        jPanel1.setBackground(new java.awt.Color(33, 37, 41));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        //jPanel3.setBackground(new java.awt.Color(164, 19, 60));
        jPanel3.setBackground(new java.awt.Color(73, 80, 87));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel3.setMaximumSize(new java.awt.Dimension(752, 540));
        jPanel3.setMinimumSize(new java.awt.Dimension(752, 540));
        jPanel3.setPreferredSize(new java.awt.Dimension(752, 540));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {270, 270};
        jPanel3.setLayout(jPanel3Layout);

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html><div style='text-align: center;'>LIBRARY MANAGEMENT SYSTEM</div></html>");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentY(1.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(54, 0, 54, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        jTextField1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jTextField1.setText("Username");
        jTextField1.setMaximumSize(new java.awt.Dimension(300, 28));
        jTextField1.setMinimumSize(new java.awt.Dimension(300, 28));
        jTextField1.setPreferredSize(new java.awt.Dimension(300, 28));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(21, 40, 21, 40);
        jPanel3.add(jTextField1, gridBagConstraints);

        //jButton1.setBackground(new java.awt.Color(128, 15, 47));
        jButton1.setBackground(new java.awt.Color(52, 58, 64));
        jButton1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOG IN");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.setMargin(new java.awt.Insets(7, 14, 7, 14));
        jButton1.setMaximumSize(new java.awt.Dimension(41, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(41, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(150, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 21, 10);
        jPanel3.add(jButton1, gridBagConstraints);

        forgetPasswordLabel.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        forgetPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        forgetPasswordLabel.setText("Forgot your password?");
        forgetPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetPasswordLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 11, 40);
        jPanel3.add(forgetPasswordLabel, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html><div style='text-align: center;'>Create an account</div></html>");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 33, 40);
        jPanel3.add(jLabel3, gridBagConstraints);

        jPasswordField1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jPasswordField1.setText("Password");
        jPasswordField1.setMaximumSize(new java.awt.Dimension(300, 28));
        jPasswordField1.setMinimumSize(new java.awt.Dimension(300, 28));
        jPasswordField1.setPreferredSize(new java.awt.Dimension(300, 28));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(21, 40, 21, 40);
        jPanel3.add(jPasswordField1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 121;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 160, 65, 160);
        jPanel1.add(jPanel3, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        try {
            conn = ConnectionManager.getConnection();
        } catch(SQLException e) {
            e.printStackTrace();
            setVisible(false);
            dispose();
        }
        
        int loggedIn = 0;
        try {
            ResultSet result = conn.createStatement().executeQuery("select UserId, UserType, FullName, PhoneNo, Address, Username, Password from UserDetails where UserName = \'" + jTextField1.getText() + "\' and Password = \'" + new String(jPasswordField1.getPassword()) + "\'");
            while (result.next()) {
                LoggedInUser.userType = result.getInt("UserType");
                LoggedInUser.userID = result.getInt("UserId");
                LoggedInUser.fullName = result.getString("FullName");
                LoggedInUser.phoneNo = result.getString("PhoneNo");
                LoggedInUser.address = result.getString("Address");
                LoggedInUser.username = result.getString("Username");
                LoggedInUser.password = result.getString("Password");
                loggedIn++;
            }
        } catch(SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Username/Password", 
                                   "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
        if (loggedIn == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Username/Password", 
                                   "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        java.text.SimpleDateFormat formatter = new java.text.SimpleDateFormat("yyyy-MM-dd");
        java.util.Date refDate = null;
        try {
            refDate = formatter.parse("1999-12-31");
        } catch (java.text.ParseException e) {
            e.printStackTrace();
        }
        
        LinkedList<Book> books = new LinkedList<>();
        try {
            ResultSet result = conn.createStatement().executeQuery("select * from Record where UserId = " + LoggedInUser.userID);
            while (result.next()) {
                Book temp = new Book();
                temp.ID = result.getInt("BookId");
                temp.borrowDate = result.getDate("BorrowDate");
                temp.returnDate = result.getDate("ReturnDate");
                temp.fine = result.getBigDecimal("Fine");
                books.add(temp);
                
                if (temp.returnDate.compareTo(refDate) == 0) LoggedInUser.borrowedBookCount++;
            }
        } catch(SQLException e) {
            e.printStackTrace();
        }
        
        try {
            for (int i = 0; i < books.size(); i++) {
                ResultSet result = conn.createStatement().executeQuery("select ISBN, Title, Description, YearPublished, Rating, Pages, ThumbnailURL from Book where BookId = " + books.get(i).ID);
                while (result.next()) {
                    Book temp = books.get(i);
                    temp.ISBN = result.getString("ISBN");
                    temp.title = result.getString("Title");
                    temp.description = result.getString("Description");
                    temp.yearPublished = result.getInt("YearPublished");
                    temp.rating = result.getFloat("Rating");
                    temp.thumbnailURL = result.getString("ThumbnailURL");
                }
            }
        } catch(SQLException e) {
            e.printStackTrace();
        }
        
        LoggedInUser.booksBorrowed = books;
        
        if (LoggedInUser.userType == 3) {
            AdminManagementPage.main(new String[] {});
            setVisible(false);
            dispose();
        } else if (LoggedInUser.userType != -1) {
            DashboardPage.main(new String[] {});
            setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusLost

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        SignupPage.main(new String[]{});
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void forgetPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPasswordLabelMouseClicked
        // TODO add your handling code here:
        ForgetPasswordPage.main(new String[]{});
        setVisible(false);
        dispose();
    }//GEN-LAST:event_forgetPasswordLabelMouseClicked

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            jButton1ActionPerformed(new java.awt.event.ActionEvent(this, 99999, "sdasd"));
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forgetPasswordLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
