/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package acp.lab.project1.pages;
import acp.lab.project1.LoggedInUser;
import acp.lab.project1.utils.ConnectionManager;
import acp.lab.project1.utils.DefinedColors;
import java.math.BigDecimal;
import java.sql.*;
import java.util.LinkedList;
/**
 *
 * @author addan
 */
public class PayFinePage extends javax.swing.JFrame {
    private BigDecimal fine;
    /**
     * Creates new form LoginForm
     */
    public PayFinePage() {
        postInit();
        initComponents();
    }
    
    private void postInit() {
        try {
            Connection con = ConnectionManager.getConnection();
            ResultSet rs = con.createStatement().executeQuery("select sum(fine) as c from Record where UserId = " + LoggedInUser.userID);
            while (rs.next()) {
                fine = rs.getBigDecimal("c");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        payButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        // jPanel1.setBackground(new java.awt.Color(89, 13, 34));
        jPanel1.setBackground(DefinedColors.backgroundPrimaryColor);
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 420));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        //jPanel3.setBackground(new java.awt.Color(164, 19, 60));
        jPanel3.setBackground(DefinedColors.backgroundLightColor);
        jPanel3.setBorder(new javax.swing.border.LineBorder(DefinedColors.whiteColor, 1, true));
        jPanel3.setMaximumSize(new java.awt.Dimension(752, 540));
        jPanel3.setMinimumSize(new java.awt.Dimension(752, 540));
        jPanel3.setPreferredSize(new java.awt.Dimension(752, 540));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {270, 270};
        jPanel3.setLayout(jPanel3Layout);

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(DefinedColors.whiteColor);
        jLabel1.setText("<html><div style='text-align: center;'>Pay Fines</div></html>");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentY(1.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 20, 50);
        jPanel3.add(jLabel1, gridBagConstraints);

        amountField.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        amountField.setText("Amount");
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        jPanel3.add(amountField, gridBagConstraints);

        //jButton1.setBackground(new java.awt.Color(128, 15, 47));
        backButton.setBackground(DefinedColors.backgroundSecondaryColor);
        backButton.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        backButton.setForeground(DefinedColors.whiteColor);
        backButton.setText("Back");
        backButton.setBorder(new javax.swing.border.LineBorder(DefinedColors.whiteColor, 1, true));
        backButton.setMargin(new java.awt.Insets(7, 14, 7, 14));
        backButton.setMaximumSize(new java.awt.Dimension(150, 40));
        backButton.setMinimumSize(new java.awt.Dimension(150, 40));
        backButton.setPreferredSize(new java.awt.Dimension(150, 40));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 15);
        jPanel3.add(backButton, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel2.setForeground(DefinedColors.whiteColor);
        jLabel2.setText("Total Fine: $" + fine.toString());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        jPanel3.add(jLabel2, gridBagConstraints);

        //jButton1.setBackground(new java.awt.Color(128, 15, 47));
        payButton.setBackground(DefinedColors.backgroundSecondaryColor);
        payButton.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        payButton.setForeground(DefinedColors.whiteColor);
        payButton.setText("Pay");
        payButton.setBorder(new javax.swing.border.LineBorder(DefinedColors.whiteColor, 1, true));
        payButton.setMargin(new java.awt.Insets(7, 14, 7, 14));
        payButton.setMaximumSize(new java.awt.Dimension(150, 40));
        payButton.setMinimumSize(new java.awt.Dimension(150, 40));
        payButton.setPreferredSize(new java.awt.Dimension(150, 40));
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 15);
        jPanel3.add(payButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 121;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 160, 65, 160);
        jPanel1.add(jPanel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        acp.lab.project1.pages.DashboardPage.main(new String[]{});
        setVisible(false);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
        if (fine.compareTo(new BigDecimal(Double.parseDouble(amountField.getText()))) == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Amount entered is larger than fine!", 
                                   "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        Connection con = null;
        try {
            con = ConnectionManager.getConnection();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        if (con == null) return;
        
        try {
            int rs = con.createStatement().executeUpdate("insert into Request(RequestType, UserId, Amount) values(3, " + LoggedInUser.userID + ", " + Double.valueOf(Double.parseDouble(amountField.getText())).toString() + ");");
            System.out.println(rs + " rows inserted!");
            javax.swing.JOptionPane.showMessageDialog(this, "Admin will approve your payment within 3 business days", 
                                   "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        /*BigDecimal payment = new BigDecimal(Double.parseDouble(amountField.getText()));
        LinkedList<Integer> rid = new LinkedList<>();
        LinkedList<BigDecimal> f = new LinkedList<>();
        try {
            ResultSet rs = con.createStatement().executeQuery("select RecordId, Fine from Record where Fine > 0 and UserId = " + LoggedInUser.userID);
            while (rs.next()) {
                rid.add(rs.getInt("RecordId"));
                f.add(rs.getBigDecimal("Fine"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        for (int i = 0; i < rid.size(); i++) {
            try {
                // fine[i] is greater than remaining payment
                if (f.get(i).compareTo(payment) == 1) {
                    con.createStatement().executeQuery("update Record set Fine = Fine - " + payment.toString() + " where RecordId = " + rid.get(i));
                    break;
                }
                if (f.get(i).compareTo(payment) < 1) {
                    con.createStatement().executeQuery("update Record set Fine = 0 where RecordId = " + rid.get(i));
                    payment.subtract(f.get(i));
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }    
        }*/
    }//GEN-LAST:event_payButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayFinePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayFinePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayFinePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayFinePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayFinePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton payButton;
    // End of variables declaration//GEN-END:variables
}
